"""empty message

Revision ID: e97f810b2603
Revises: 
Create Date: 2020-06-30 16:23:50.097474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97f810b2603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('tname', sa.String(length=20), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('charge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('mname', sa.String(length=20), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('qissued', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssn_id', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('state', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssn_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('urole', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('diagnosticsmaster',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('tname', sa.String(length=20), nullable=True),
    sa.Column('tcharge', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['diagnostics.tid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('medicinemaster',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('mname', sa.String(length=20), nullable=True),
    sa.Column('qavailable', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['medicines.mid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicinemaster')
    op.drop_table('diagnosticsmaster')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('patient')
    op.drop_table('medicines')
    op.drop_table('diagnostics')
    # ### end Alembic commands ###
